DjangoApp/MovieProject/MovieProject/urls.py
from django.contrib import admin
from django.urls import path
from Movieapp import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home),
    
    path('addmovie/',views.addmovie),
    path('showmovie1/',views.showmovie),
    path('update/<int:id>',views.updatemovie),
    path('delete/<int:id>',views.deletemovie),
    path('register/',views.addUser),
    path('login/',views.Login),
    path('logout/',views.logoutUser),
    path('showuserlist/',views.showUserlist),
    path('showuserprofile/',views.showuserprofile),
    path('editprofile/',views.edituser),
    path('home/',views.home),
    path('addcart/',views.addtocart),
    path('mycart/',views.showcart),
    path('updatecart/',views.updatecart),
    path('',views.home),
    path('placeorder/',views.addorders)
    
    
    
]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DjangoApp/MovieProject/Movieapp/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User,Group

# Create your models here.

class Movie(models.Model):
    name=models.CharField(max_length=20)
    certificate=models.CharField(choices=[('U/A','U/A'),('A','A')],max_length=3)
    type=models.CharField(max_length=10)
    language=models.CharField(max_length=10)
    duration=models.CharField(max_length=20)
    director=models.CharField(max_length=20)
    cast=models.CharField(max_length=50)
    description=models.CharField(max_length=1000)
    #select_date=models.DateField()
    #select_time=models.TimeField()
    Price=models.IntegerField()
    Image=models.ImageField(upload_to='media')
    
    #select_date_and_time=models.DateField(auto_now_add=True)
    
    
    class Meta:
        db_table='movie'
        
    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    location = models.CharField(max_length=20)
    number = models.IntegerField()
    
    class Meta:
        db_table='UserProfile'
        
        
admin, status = Group.objects.get_or_create(name='admin')
customer, status = Group.objects.get_or_create(name='customer')

class Cart(models.Model):
    movieobject=models.ForeignKey(Movie,on_delete=models.CASCADE)
    userObject=models.ForeignKey(User,on_delete=models.CASCADE)
    number_of_ticket=models.IntegerField(default=1)
    totalprice=models.FloatField()
    
    class Meta:
        db_table='cart'
    def __str__(self) :
        return str(self.userObject)

DjangoApp/MovieProject/Movieapp/forms.py
from dataclasses import fields
from django import forms
from .models import Movie, UserProfile,User



class movieform(forms.ModelForm):
    
    class Meta:
        model=Movie
        fields="__all__"
        
class Userform (forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','password','email']
     
        
class UserProfileForm(forms.ModelForm):
    role1=[('customer','customer'),('admin','admin')]
    role=forms.ChoiceField(widget=forms.RadioSelect(),choices=role1)
    
    class Meta:
        model = UserProfile
        fields = ['location', 'number']
        

DjangoApp/MovieProject/Movieapp/views.py
from enum import Flag
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Movie,User,UserProfile,Cart
from .forms import movieform,UserProfileForm,Userform
from django.contrib.auth.models import Group
from django.contrib import messages
from django.db.models import Sum
from django.http import JsonResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from MovieProject.settings import RAZORPAY_API_KEY,RAZORPAY_API_SECRET_KEY
import razorpay
client = razorpay.Client(auth=(RAZORPAY_API_KEY, RAZORPAY_API_SECRET_KEY ))

# Create your views here.

def addmovie(request):
    form=movieform()
    if request.method=="POST":
        print(request.FILES)
        form=movieform(request.POST,request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponse('<h1>Saved</h1>')
    
    return render(request,'movieapp/addmovie.html',{'mform':form})

def showmovie(request):
    data=Movie.objects.all
    return render (request,'movieapp/showmovie1.html',{'showmovie':data})

def updatemovie(request,id):
    movie=Movie.objects.get(id=id)
    form=movieform(instance=movie)
    if request.method=='POST':
        print(request.FILES)
        print('-------------')
        form=movieform(request.POST,request.FILES,instance=movie)
        if form.is_valid():
            print('-------------')
            form.save(commit=True)
            return redirect('/showmovie')

    return render(request,'movieapp/addmovie.html',{'mform':form})

def deletemovie(request,id):
    data=Movie.objects.get(id=id)
    data.delete()
        
    return redirect('/showmovie')


def addUser(request):
    uform = Userform()
    custform =UserProfileForm()
    
    if request.method=='POST':
    
        role = request.POST['role']
        uform = Userform(request.POST)
        custform=UserProfileForm(request.POST)
        
        if uform.is_valid() and custform.is_valid():
            email = request.POST.get('email')
            if User.objects.filter(email=email).exists():
                messages.warning(request,'This email already exist')
            else:
                uobj = uform.save(commit=True)
                uobj.set_password(uobj.password)
                uobj.save()
                userobj=custform.save(commit=False)
                userobj.user=uobj
                userobj.save()
                if role == 'customer':
                    cust = Group.objects.get(name='customer')
                    uobj.groups.add(cust)
                elif role == 'admin':
                    admin = Group.objects.get(name='admin')
                    uobj.groups.add(admin)

    return render(request, 'movieapp/register.html', {'uform': uform, 'form': custform})    

def Login(request):
    form=AuthenticationForm()
    if request.method=="POST":
        uname=request.POST['username']
        pwd=request.POST['password']
        print(uname,pwd)
        
        user=authenticate(username=uname,password=pwd)
        if user!=None:
            login(request,user)
            return redirect('/showmovie1/')
        else:
            msg="INVALID USERNAME AND PASSWORD"
            return render(request,"movieapp/login.html",{'form':form, 'msg':msg})
        
    return render(request,"movieapp/login.html",{'form':form})   



def logoutUser(request):
    print('..............',request.user)
    logout(request)

    return redirect('/login/')   

def showUserlist(request):
    data=UserProfile.objects.all
    return render(request, 'movieapp/customerlist.html',{'users':data})

def showuserprofile(request):
    currentuser=request.user
    print(currentuser)
    userobject=UserProfile.objects.get(user=currentuser)
    print(userobject.user.email)
    groupobj=str(Group.objects.get(user=currentuser))
    print(groupobj,type(groupobj))
    return render(request,'movieapp/userprofile.html',{'user':userobject,'role':groupobj})


def edituser(request):
    currentuser=request.user
    print(currentuser)
    data = UserProfile.objects.get(user=currentuser)
    data1=User.objects.get(username=currentuser)
    if request.method=='POST':
        print(request.POST)
        uform = Userform(request.POST,instance=data1)
        form = UserProfileForm(request.POST,instance=data)
        print(uform)
        print(form)
        if uform.is_valid() and form.is_valid():
            uobj = uform.save(commit=True)

            uobj.save()
            userobj = form.save(commit=False)
            userobj.user = uobj
            userobj.save()
    return redirect('/index/')

    
def home(request):
     return render(request,'movieapp/home.html')

# def booking(request,id):
#     movie=Movie.objects.get(id=id)
#     form=movieform(instance=movie)    
#     print(movie)
#     return render(request,'movieapp/booking.html',{"data":movie})

def addtocart(request):
    print(request)
    mid=request.GET.get('movieid')
    movieobject=Movie.objects.get(id=mid)
    movieprice=movieobject.Price
    userobject=request.user
    print(movieobject,userobject,movieprice)
    Cart(movieobject=movieobject,userObject=userobject,totalprice=movieprice).save()
    return redirect('/showmovie1')


def showcart(request):
   items=Cart.objects.filter(userObject=request.user)
   flag=items.exists()
   if request.method=="POST":
       customer=UserProfile.objects.get(user=request.user)
      
       totalam=request.POST.get('totalamount')
       DATA = {
        "amount": int(totalam)*100,
        "currency": "INR",
        "receipt": "receipt#1",
        "notes": {
            "key1": "value3",
            "key2": "value2"}}
       orderObject=client.order.create(data=DATA)  
       print(orderObject)
       orderid=orderObject['id']
       
       return render(request,'movieapp/payment.html',{'ordid':orderid,'customer':customer,'apiKey':RAZORPAY_API_KEY,'amount':totalam})
   return render(request,'movieapp/mycart.html',{'items':items,'flag':flag})  


def updatecart(request):
    p=request.POST.get('price')
    q=request.POST.get('qnt')
    id=request.POST.get('cid')
    totalprice=float(p)*int(q)
    Cart.objects.filter(id=id).update(number_of_ticket=q,totalprice=totalprice)
    total=Cart.objects.filter(userObject=request.user).aggregate(Sum('totalprice'))
    print(total)
    totalamount=total['totalprice__sum']

    return JsonResponse({'status':True,'totalprice':totalprice,'totalam':totalamount})


def addorders(request):
    print(request)

DjangoApp/MovieProject/templates/movieapp/addmovie.html
<!DOCTYPE html>

<html>
    <head>
  
    </head>
    <body>
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
                 {{mform.as_p}}
            <input type="submit">
        </form>
    </body>
</html>

DjangoApp/MovieProject/templates/movieapp/booking.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        {% include 'movieapp/home.html' %}
    </head>
    <body>
        
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title" >Card title</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">An item</li>
              <li class="list-group-item">A second item</li>
              <li class="list-group-item">A third item</li>
            </ul>
            <div class="card-body">
              <a href="#" class="card-link">BOOK NOW</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
    </body>
</html>

DjangoApp/MovieProject/templates/movieapp/customerlist.html
<!DOCTYPE html>
<html lang="en">
<head>
 

</head>
<body>
<div>
</div>
<div class="container">
<h1 align="center">OUR CLIENT</h1>
<table class="table table-hover">
    <thead>
    <tr>

        <td>Username</td>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Email</td>
        <!--<td>Password</td>-->
        <td>location</td>
        <td>Contact Number</td>

    </tr>
    </thead>
    <tbody>
    {% for i in users %}
    <tr>
        <td>{{i.user.username}}</td>
        <td>{{i.user.first_name}}</td>
        <td>{{i.user.last_name}}</td>
        <td>{{i.user.email}}</td>
        <td hidden>{{i.user.password}}</td>

        <td>{{i.location}}</td>
        <td>{{i.number}}</td>
    </tr>
    {% endfor %}

    </tbody>




</table>




</div>


</body>
</html>

DjangoApp/MovieProject/templates/movieapp/header.html
<!DOCTYPE html>
<html>
    <head>
        <!-- CSS only -->
        
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <style>
        
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Ticket Booking</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/showmovie/">Movies</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/login/">LOGIN</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/register/">REGISTER</a>
                
              </div>
            </div>
          </nav>

         
        
    </body>
</html>

DjangoApp/MovieProject/templates/movieapp/home.html
<!DOCTYPE html>
<html>
    <head>
   
                
    </head>
    {% include 'movieapp/navbar.html' %}

    </body>
</html>

DjangoApp/MovieProject/templates/movieapp/index.html
<html>
    <head>
 
    </head>
    <body>
      <h1>WELCOME</h1>
    </body>
</html>

DjangoApp/MovieProject/templates/movieapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Login</title>
</head>

{% include 'movieapp/home.html' %}
<body>

<form method="Post"  class="form-control" align="center" >
    <h3 style="color:red">{{msg}}</h3>
     {% csrf_token %}
        {{form.as_p}}
    <input type="submit">
</form>
</body>
</html>

DjangoApp/MovieProject/templates/movieapp/mycart.html
<!DOCTYPE html>
{% load static %} 
<html>
    {% include 'movieapp/header.html' %}
    <head>
        <style>
        
        </style>
    </head>
    <body>
      {% if flag %}
     
      <form method='POST'>
        {% csrf_token %} 
        <table class="table">
            <thead>
              <tr>
                <th scope="col">MOVIE</th>
                <th scope="col">Price</th>
                <th scope="col">Seats</th>
                <th scope="col">Total Price</th>
</tr>
            </thead>
            <tbody>
                {% for item in items %}
              <tr>
                <td ><img src="{{item.movieobject.Image.url}}"  height="500" width="400px"> 
                  <br><h4>{{item.movieobject.name}}</h4></td>
                <td>{{item.movieobject.Price}}</td>
               
                <td ><input type="number" min='0'  value="{{item.number_of_ticket}}" cartid="{{item.id}}" class="qnt" id='qnt{{item.id}}'/></td>
                <td ><input type="text" value=" {{item.totalprice}}" id="totalprice{{item.id}}" class='totalprice' /></td>
                <td><a href="#">Delete</a></td>
              </tr>
              {% endfor %}
            
            </tbody>
          </table>
        
          <label>Totalmount</label>
          <input type="text" name='totalamount' id='totalamount' value='0.0'/>
          <input type="submit"  value="Placeorder">
          </form>
          
          {% else %}
          <h1>Empty cart</h1>
          {% endif  %}
         <script>
            $(document).ready(function(){
              
              $('.qnt').change(function(){
                
                quantity=$(this).val()
                price=$(this).parent().prev().html()
                
                id=$(this).attr('cartid')
               // $("#totalprice"+id).val(totalprice)
               $.ajax({
                 url:"/updatecart/",
                 method:'POST',
                 data:{'qnt':quantity,'price':price,'cid':id,'csrfmiddlewaretoken':'{{csrf_token}}'},
                 success:function(response){
                  $("#totalprice"+id).val(response.totalprice);                 
                  $('#totalamount').val(response.totalam);
                 },
                 error:function(){}
               })
               
              })
            })
          </script>
    </body>
    </html>

DjangoApp/MovieProject/templates/movieapp/payment.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        {% include 'movieapp/navbar.html' %}
        
       <!--razorpay script code-->
         
        <form action="/placeorder/" method="POST">
          {% csrf_token%}
          <input type="text" name='amount' value="{{amount}}">
     
          <script    src="https://checkout.razorpay.com/v1/checkout.js"    
          data-key="{{apiKey}}"   
          data-amount="29935" 
          data-currency="INR"
          data-order_id="{{ordid}}"   
          data-buttontext="Pay with Razorpay"    
          data-name="BOOKMYSHOW"    
          data-description="Book any show"    
          data-image="https://example.com/your_logo.jpg"   
          data-prefill.name="{{customer.user.username}}"    
          data-prefill.email="{{customer.user.email}}"   
          data-theme.color="#F37254">
        </script><input type="hidden" custom="Hidden Element" name="hidden"></form>
        </body>
</html> 

DjangoApp/MovieProject/templates/movieapp/showmovie.html
<!DOCTYPE html>

<html>
    <head>
     
    </head>
    <div>
      
{% include 'movieapp/home.html' %}
    </div>
    <body>
     <!--{{showmovie}}-->
     {% comment %} <table border="1" cellpadding='5px' class="table table-striped table-hover">
        <thead>
          <tr> 
          
            <th></th>
            <th>TYPE</th>
            <th>LANGUAGE</th>
            <th>DURATION</th>
            <th>CAST</th>
            <th>DESC</th>
            <th>PRICE</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for i in showmovie %}
        <tr>
           
            <td>
              <label>{{i.name}}</label><br><br>
              <img src='{{i.Image.url}}' height="150px" width="150">

            
            <td>{{i.type}}</td>
            <td>{{i.language}}</td>
            <td>{{i.duration}}</td>
            <td>{{i.cast}}</td>
            <td>{{i.description}}</td>
            <td>{{i.Price}}</td>
            <td>
            <a href='/update/{{i.id}}'>Edit</a>
            <a href="/delete/{{i.id}}">Delete</a>
            </td>
            
        </td>
        
        {% endfor %}
 {% endcomment %}
 {% for i in showmovie %}

 <div class="container mt-4">
     <div class="card mb-2" style="max-width: 1150px;">
   <div class="row g-1">
     <div class="col-md-4" style="background-color: #8e8fe8">
      <img src="{{i.Image.url}}" style="width: 300px; height: 20rem;" class="card-img-top img-fluid">
     </div>
     <div class="col-md-8">
       <div class="card-body" style="background-color: pink">
 
         <h5 class="card-title">{{ i.name }}</h5>
         <p class="card-text">{{i.description}}

         </p>
         <p class="card-text"><small class="text-muted">Last booked 3 mins ago</small></p>
           <p class="card-text"><b>Director: </b>{{i.director}} &nbsp;&nbsp;&nbsp;
             <b>Type:</b>     &nbsp;{{i.type}}&nbsp;&nbsp;&nbsp;&nbsp;
           <b>Price:</b> &nbsp;{{i.Price}}&nbsp;Rs
           </p>
           <br>
           {% comment %} {% if perms.movieapp.addcart %} {% endcomment %}
           <a href="#" class="addtocart" id="{{movie.id}}"><i class="fas fa-cart-plus"></i></a>
             {% comment %} <a href="#" > class="addtocart" <i class="fas fa-cart-plus"></i></a> {% endcomment %}
            {% comment %} {% endif %} {% endcomment %}
            
           {% comment %} {% if perms.movieapp.delete_movie %} {% endcomment %}

            <a href="/update/{{i.id}}" class="btn btn-success" >Update</a>
             <a href="/delete/{{i.id}}" class="btn btn-danger" >Delete</a>
             {% comment %} {% endif %} {% endcomment %}
       </div>
     </div>
   </div>
 </div>
     </div>
 </div>
 {% endfor %}
 {% comment %} <script>
  $(document).ready(function(){
  $('.addtocart').click(function(){
      alert('clicked')
  {% comment %} $.ajax({
 url:'/booking',
 method:'GET' ,
 data:{'movieid':$(this).attr('id')},
 success:function()
 {
 alert('movie added to booking summary...')
 },
 error:function(){}, {% endcomment %}


</script> 
<script>
  $(document).ready(function(){
    $(".addtocart").click(function(){
      var id=$(this).attr('id')
     
      $.ajax({
        url:'/addcart',
        method:'GET',
        data:{'movieid':id},
        success:function(){alert('Item added to the cart')}

      })    
    })
  })
</script>
    </body>
</html>

DjangoApp/MovieProject/templates/movieapp/showmovie1.html
<!DOCTYPE html>
<html>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <head></head>
    <body>
      {% include 'movieapp/navbar.html' %}
      <table border="1" cellpadding='5px' class="table table-striped table-hover">
          <thead>
            <tr> 
            
              <th>Name</th>
              <th>certificate</th>
              <th>type</th>
              <th>LANGUAGE</th>
              <th> duration</th>
              <th> director</th>
              <th>cast</th>
              <th> discrrotipn</th>
              <th>price</th>
            </tr>
          </thead>
            <tbody>
            {% for movie in showmovie %}
            <tr>
           
            <td>
              <label>{{movie.name}}</label><br><br>
              <img src='{{movie.Image.url}}' height="150px" width="150"> 

            </td>
            <td>{{movie.certificate}}</td>
            <td>{{movie.type}}</td>
            <td>{{movie.language}}</td>
            <td>{{movie.duration}}</td>
            <td>{{movie.director}}</td>
            <td>{{movie.cast}}</td>
            <td>{{movie.description}}</td>

            <td>
              {% if perms.movieapp.delete_movie %}
                <a href='/update/{{movie.id}}'>Edit</a>
                <a href="/delete/{{movie.id}}">Delete</a>
                {% endif %}
                
                {% comment %} {% if perms.movieapp.add_movie %} {% endcomment %}

                <a href="#" class="addtocart" id="{{movie.id}}"><i class="fas fa-cart-plus"></i></a>
                {% comment %} {% endif %} {% endcomment %}
                </td>
         </tr>
            {% endfor %}
            
          </tbody>
        </table>
        <script>
          $(document).ready(function(){
            $(".addtocart").click(function(){
              var id=$(this).attr('id')
              $.ajax({
                url:'/addcart',
                method:'GET',
                data:{'movieid':id},
                success:function(){alert('Movie added to the BOOKING SUMMARY')}
            })
          })
        })
          
        </script>
        </body>
    </html>
            
            

DjangoApp/MovieProject/templates/movieapp/userprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
<div>
</div>
<div class="container">
<form method="post" action="/editprofile/">
    {% csrf_token %}

<p><label >Username:</label>

    <input type="text" name="username" maxlength="150" required id="id_username" value="{{user.user.username}}">
<p><label for="id_first_name">First name:</label>
    <input type="text" name="first_name" maxlength="30" id="id_first_name" value="{{user.user.first_name}}"></p>
<p><label >Last name:</label>

    <input type="text" name="last_name" maxlength="150" id="id_last_name" value="{{user.user.last_name}}"></p>
    <input type="hidden" name="password" maxlength="10" required " value="{{user.user.password}}">
<p><label for="id_email">Email address:</label>
    <input type="email" name="email" maxlength="254" id="id_email" value="{{user.user.email}}"></p>
    <p><label for="id_location">Location:</label>
        <input type="text" name="location" maxlength="50" required id="id_location" value="{{user.location}}"></p>
<p><label for="id_number">Number:</label>
    <input type="hidden" name="user" maxlength="10" required id="id_number" value="{{user.user}}">
    <input type="text" name="number" maxlength="10" required id="id_number" value="{{user.number}}"></p>
<p>
    <select name="role">
    {% if role == 'customer' %}
        <option>{{role}}</option>
        <option>Admin</option>

        {% else %}
         <option>{{role}}</option>
        <option>Customer</option>
        {% endif %}
    </select>
</li>
<input type="submit" value="update">

    </li>
</li>
</ul></p>
</form>
</div>

</body>
</html>